# Generated by Django 5.0 on 2024-03-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='expire_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
