# Generated by Django 5.0 on 2024-03-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='caption',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
